import type { Metadata } from "next";
import "./globals.css";
import { Vazirmatn } from "@/public/fonts/vazirLocalFont/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`font-vazir  bg-dark-900 text-stone-100 ${Vazirmatn.variable} `}
      >
        {children}
      </body>
    </html>
  );
}
